### ISSUE TITLE
District API reports wrong Invasion Cog

### ISSUE THREAD

**Issue by saltyTT** [CorporateClash/api-docs#2]
When there is an invasion, the api responds with the correct cog tier but not the correct department.

For example, if Double Talkers were invading, the api would report it as Tightwads.
Both cogs are tier 3 in their department, however the department is consistently one lesser.

_Actual Department : API Reported Department_
Sellbot : Boardbot
Cashbot : Sellbot
Lawbot : Cashbot
Bossbot : Lawbot
Boardbot : Bossbot

**Comment by judge2020** [comment]
Cog department indexes were changed around during rebrand, will be fixing this.

**Comment by judge2020** [comment]
Fixed with v1.0.7. Boardbots used to be index 4, at the bottom of the cog list, while now they're index 0 above Bossbots.
