### ISSUE TITLE
Breaking Districts API change - 09/15/2018

### ISSUE THREAD

**Issue by judge2020** [CorporateClash/api-docs#3]
Recently the web server had a misfunctioning district tracker hit the servers. Since moving to AWS I forgot to re-confirm the district API caching worked causing error rates (on non-district API requests) to hit 10% due to the server being overloaded. 

Since the tracker used the query string trick to bypass the cache (appending `?randNumber`), the Cloudflare cache didn't work. The setting was always "cache everything" with a short 10 second, however, the query string caused requests to always hit the origin.

Changes made

* URL

Due to how [Cloudflare caching works](https://support.cloudflare.com/hc/en-us/articles/200172516-Which-file-extensions-does-Cloudflare-cache-for-static-content-), the URL has changed to add a `.js` to the end. With this, we can set the cache level to "bypass query string", and keep the load off our server.

* redirecting old API

A redirect was made via Cloudflare, however, if your tracker is done via Javascript this will likely not work due to the `Access-Control-Allow-Origin` not being present in the 301 redirect. If you have a script or server-based API that follows redirects, you should be good to go.

---

Sorry for any inconvenience caused, this issue will be closed after 30 days.

**Comment by AnonymousDeveloper13** [comment]
"after 30 days" lmao did u forget? its been a year
