### ISSUE TITLE
API is just broke.

### ISSUE THREAD

**Issue by DatPiggy** [CorporateClash/api-docs#4]
I'm sure you realize this, but the API is completely broken. It does not report correct invasions/cog types at all.

**Comment by judge2020** [comment]
The game stopped reporting the correct cog name back in April due to a code change, and the incorrect department was fixed about a month ago. Within the next few days, when we do a server restart, the change will be live and it should start reporting correct cog names.

**Comment by DatPiggy** [comment]
Great! Thanks for the update and your hard work :)
